server:
  port: 8090
spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # OSIV 설정 끄기
services:
  auth:
    url: http://43.203.126.129:8090  # 인증 서비스 URL
  #    url: http://localhost:8091  # 인증 서비스 URL
  noti:
    url: http://43.203.126.129:8097  # 인증 서비스 URL
  post:
    url: http://43.203.126.129:8093  # 인증 서비스 URL
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:51333333373"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: pawpaw.kknaks.site
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    name: "PawPaw"
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"