server:
  port: 8091
spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: prod
    include: secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB   # 개별 파일 최대 크기
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            scope:
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "${custom.site.backUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Kakao    # 클라이언트 이름
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me    # 사용자 정보 조회 URI
            user-name-attribute: id    # 사용자 정보에서 사용자 이름에 해당하는 속성
  kafka:
    bootstrap-servers: 43.203.126.129:19092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.ll.hereispaw.domain.noti.dto.kafka
        spring.json.use.type.headers: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로
  api-docs:
    path: /api-docs        # API 문서 경로
logging:
  level:
    root: info
    com.ll.hereispaw : debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:513373"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: pawpaw.kknaks.site
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    name: "PawPaw"
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"