spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # OSIV 설정 끄기

logging:
  level:
    root: info
    com.ll.hereispaw : debug
services:
  auth:
    url: http://localhost:8090 # 인증 서비스 URL
  post:
    url: http://localhost:8093  # 게시글 서비스 URL
  chat:
    url: http://localhost:8095  # 채팅 서비스 URL
  noti:
    url: http://localhost:8097  # 알림 서비스 URL
  payment:
    url: http://localhost:8099 # 결제 서비스 URL