server:
  port: 8090
spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # OSIV 설정 끄기
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:51333333373"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: pawpaw.kknaks.site
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    name: "PawPaw"
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
services:
  auth:
    url: http://110.165.16.61:8090 # 인증 서비스 URL
  post:
    url: http://110.165.16.61:8093  # 게시글 서비스 URL
  chat:
    url: http://110.165.16.61:8095  # 채팅 서비스 URL
  noti:
    url: http://110.165.16.61:8097  # 알림 서비스 URL
  payment:
    url: http://110.165.16.61:8100 # 결제 서비스 URL
  search:
    url: http://110.165.16.61:8103  # 검색 서비스 URL
  carecenter:
    url: http://110.165.16.61:8105 # 병원 서비스 URL